export const BOARD_LIST_REQUEST = 'BOARD_LIST_REQUEST';
export const BOARD_LIST_SUCCESS = 'BOARD_LIST_SUCCESS';
export const BOARD_LIST_FAIL = 'BOARD_LIST_FAIL';

export const BOARD_ITEM_REQUEST = 'BOARD_ITEM_REQUEST';
export const BOARD_ITEM_SUCCESS = 'BOARD_ITEM_SUCCESS';
export const BOARD_ITEM_FAIL = 'BOARD_ITEM_FAIL';