export const TODO_LIST_REQUEST = 'TODO_LIST_REQUEST';
export const TODO_LIST_SUCCESS = 'TODO_LIST_SUCCESS';
export const TODO_LIST_FAIL = 'TODO_LIST_FAIL';

export const TOOL_ITEM_REQUEST = 'TOOL_ITEM_REQUEST';
export const TOOL_ITEM_SUCCESS = 'TOOL_ITEM_SUCCESS';
export const TOOL_ITEM_FAIL = 'TOOL_ITEM_FAIL';
export const TOOL_SAVE_SUCCESS = 'TOOL_SAVE_SUCCESS';